"""empty message

Revision ID: 1af895a7bbfb
Revises: d22e9e7dad48
Create Date: 2017-05-25 08:02:51.811623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af895a7bbfb'
down_revision = 'd22e9e7dad48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'roles', ['name'], unique=True)
    # ### end Alembic commands ###
