"""empty message

Revision ID: 24dab7590f79
Revises: 
Create Date: 2017-05-03 06:16:24.265103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24dab7590f79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('published_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'published_date')
    op.drop_column('posts', 'is_published')
    op.drop_column('posts', 'is_archived')
    # ### end Alembic commands ###
