"""empty message

Revision ID: d22e9e7dad48
Revises: 623bfd3769bf
Create Date: 2017-05-25 08:00:54.101324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd22e9e7dad48'
down_revision = '623bfd3769bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='privileges')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'privileges', ['name'], unique=True)
    # ### end Alembic commands ###
